---

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ config_attributes.azure.resource_group | default(resource_group) }}"
        name: "{{ config_attributes.azure.vm_nsg | default(vm_nsg) }}"
        rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound