---
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vm_publicIP }}"
      register:  reg_publicIP
      
    - debug: var=reg_publicIP