---
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ az }}"
        tags:
          testing: testing
          delete: never