---
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ config_attributes.azure.resource_group | default(resource_group) }}"
        name: "{{ config_attributes.azure.vm_name | default(vm_name) }}"
        vm_size: "{{ config_attributes.azure.vm_size | default(vm_size) }}"
        admin_username: "{{ config_attributes.azure.username | default(username) }}"
        admin_password: "{{ config_attributes.azure.password | default(password) }}"
    #   network_interfaces: "{{ vm_NIC }}"
        image:
            offer: "{{ vm_offer }}"
            publisher: "{{ vm_pub }}"
            sku: "{{ vm_sku }}"
            version: latest