---

   - name: create a address
     gcp_compute_address:
        name: "{{ address_instance }}"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
            - https://www.googleapis.com/auth/compute
        state: present
     register: address