---
    - name: Launch the new EC2 Instance
      ec2: 
        group: "{{ config_attributes.aws.security_group | default(security_group) }}" 
        instance_type: "{{ instance_type}}"
        image: "{{ image }}" 
        wait: true 
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{count}}"
                 
      register: ec2
